### ISSUE TITLE
Add font style to the page

### ISSUE THREAD

**Issue by izabelalungu** [izabelalungu/Edland#2]
Should choose a font and use it into the page.
Example for font:
https://fonts.google.com/specimen/Poppins?preview.text=Creati%20casa%20visurilor%20voastre&preview.size=30&preview.text_type=custom&query=poppins&category=Serif,Sans+Serif,Display&subset=latin&noto.script=Latn

**Comment by akj2018** [comment]
Hi, can you assign this issue to me. I can help you.
Thank You

**Comment by karthickbharathi1** [comment]
Hey @izabelalungu ,Could you please assign this issue to me. I solved the issue and would like to contribute. I have made a PR.

**Comment by izabelalungu** [comment]
Hi,
Thank you both :> I approved [akj2018](https://github.com/akj2018)'s code.
Well done both.
